In [6]:
import pandas as pd
from stroke_prediction import train, inference

df_t = pd.read_csv("../data/healthcare-dataset-stroke-data.csv")
df = pd.read_csv("../data/test_data_null.csv")

In [7]:
train.make_model(df_t)

0.8329297820823245

In [8]:
inference.make_prediction(df)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [37]:
import numpy as np
A = np.arange(0,569*3).reshape(569,3)
B=np.arange(0,3)

In [38]:
B=B.reshape(1,3)

In [36]:
for i in range (A.shape[1]):
    A[:,i] = A[:,i] * B[0,i]
    



array([[   0,    5,    8],
       [   0,   20,   20],
       [   0,   35,   32],
       ...,
       [   0, 8495, 6800],
       [   0, 8510, 6812],
       [   0, 8525, 6824]])

[array([[   0,    1,    2, ..., 1704, 1705, 1706],
        [   0,    1,    2, ..., 1704, 1705, 1706],
        [   0,    1,    2, ..., 1704, 1705, 1706]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [2, 2, 2, ..., 2, 2, 2]])]

In [34]:

B[0,1]

1